export LD_LIBRARY_PATH=/data/vision/billf/object-properties/sound/software/libQGLViewer-2.6.4/QGLViewer:/data/vision/billf/object-properties/sound/software/lib:/data/vision/billf/object-properties/sound/software/mkl/mkl/lib/intel64:$LD_LIBRARY_PATH

PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]\$\[\033[0m\] '
PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;36m\]>>\[\033[0m\] '
alias ls='ls --color -GFh'
LS_COLORS='di=1;31:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=36:*.rpm=90'
export LS_COLORS

export CPLUS_INCLUDE_PATH=/data/vision/billf/object-properties/sound/software/mkl/compilers_and_libraries_2017.0.098/linux/mkl/include/:/data/vision/billf/object-properties/sound/software/tbb/compilers_and_libraries_2017.0.098/linux/tbb/include/:/data/vision/billf/object-properties/sound/code/ModalSound/src/:/data/vision/billf/object-properties/sound/software/FEAST/3.0/include/:$CPLUS_INCLUDE_PATH

alias demo='cd /data/vision/billf/object-properties/sound/sound/code/ModalSound/src/demo'
alias build='cd /data/vision/billf/object-properties/sound/sound/code/ModalSound/build'
alias bin='cd /data/vision/billf/object-properties/sound/sound/code/ModalSound/build/bin'
alias torch='~/bin/luajit'
alias sound='cd /data/vision/billf/object-properties/sound/'
alias sound_dir='/data/vision/billf/object-properties/sound'
alias prim='cd /data/vision/billf/object-properties/sound/sound/primitives'
alias inf='cd /data/vision/billf/object-properties/sound/sound/primitives/code/inference/'

export LIB_PATH=/data/vision/billf/object-properties/local/lib:$LIB_PATH
export OBJ_PATH=/data/vision/billf/object-properties
export RECOG_PATH=/data/vision/billf/jwu-recog
export BIN_PATH=/data/vision/billf/object-properties/local/lib:$BIN_PATH
export BIN_PATH=$OBJ_PATH/bin:$BIN_PATH
export LIB_PATH=$OBJ_PATH/lib:$LIB_PATH
export LOCAL_PATH=$OBJ_PATH/local

export LD_LIBRARY_PATH=/data/vision/billf/object-properties/local/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/glog-0.3.3/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/cuda-5.5/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/cuda-6.5/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/cuda-7.0/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/cuda-7.5/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/cudnn-6.5-v2-rc2:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/cudnn-4.0.7/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/cudnn-5.0.5/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/freeglut-3.0.0/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/glew-1.10.0/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/glew-1.13.0/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/composer_xe_2013_sp1.1.106/mkl/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/ALE:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/lib:$LD_LIBRARY_PATH
export KMP_DUPLICATE_LIB_OK=TRUE

export PATH=/data/vision/billf/object-properties/local/lib:$PATH
export PATH=/afs/csail.mit.edu/system/amd64_linux26/matlab/latest/bin:$PATH
export PATH=$LIB_PATH/aws-mturk-clt-1.3.1/bin:$PATH
export PATH=$LOCAL_PATH/bin:$PATH
export PATH=$BIN_PATH:$PATH

export ODE_PATH=$LOCAL_PATH/ode-0.13
export PATH=$ODE_PATH/bin:$PATH
export LD_LIBRARY_PATH=$ODE_PATH/lib:$LD_LIBRARY_PATH

export CAFFE_PATH=$LIB_PATH/caffe
export PYTHONPATH=$CAFFE_PATH/python:$PYTHONPATH

export PYTHON_PATH=$LOCAL_PATH/lib/python2.7
export PYTHONPATH=$PYTHON_PATH/site-packages:$PYTHONPATH
export PYTHONPATH=$PYTHON_PATH/dist-packages:$PYTHONPATH
export PYTHONPATH=$LIB_PATH/util/py:$PYTHONPATH

export TORCH_PATH=$LIB_PATH/torch/install
export LUA_PATH=$TORCH_PATH/share/luajit-2.1.0-alpha/?.lua\;$LUA_PATH
export LUA_PATH=$LIB_PATH/util/lua/?.lua\;$LUA_PATH
export LUA_PATH=./?.lua\;$LUA_PATH
export LUA_PATH=$TORCH_PATH/share/lua/5.1/?/init.lua\;$LUA_PATH
export LUA_PATH=$TORCH_PATH/share/lua/5.1/?.lua\;$LUA_PATH

export LUA_CPATH=./?.so\;$LUA_CPATH
export LUA_CPATH=$LOCAL_PATH/Malmo-0.17.0/Lua_Examples/?.so\;$LUA_CPATH
export LUA_CPATH=$TORCH_PATH/lib/lua/5.1/?.so\;$LUA_CPATH
export LUA_CPATH=$TORCH_PATH/lib/?.so\;$LUA_CPATH

export PATH=$TORCH_PATH/bin:$PATH
export LD_LIBRARY_PATH=$TORCH_PATH/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/data/vision/billf/object-properties/local/lib:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$TORCH_PATH/lib:$DYLD_LIBRARY_PATH

export ANACONDA_PATH=$LIB_PATH/anaconda2
export PATH=$ANACONDA_PATH/bin:$PATH
export LD_LIBRARY_PATH=$ANACONDA_PATH/lib:$LD_LIBRARY_PATH
export PATH=/usr/bin:$PATH

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export LD_LIBRARY_PATH=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/data/vision/billf/object-properties/sound/zhengjia/nvidia-340:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/data/vision/billf/object-properties/sound/zhengjia:$LD_LIBRARY_PATH
